image:
  repository: hello-world-img
  tag: latest

replicaCount: 2

service:
  name: hello-world-svc
  type: NodePort // Use http://<minikube-ip>:<node-port> for accessing the hello-world-svc
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
