image:
  repository: your-docker-repo/hello-world-img
  tag: latest

replicaCount: 2

service:
  name: hello-world-svc
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
